# @package _global_

# order in which configs override each other (/* - denotes a relative search path)
defaults:
  - base_ours
  - /dataset: colmap
  - /initialization: colmap
  - _self_

# overwrite of default parameters
val_frequency: 1095 